#!/usr/bin/python
# -*- coding: utf-8 -*-

languages = {
    'Afrikaans': 'af_ZA',
    'Arabic': 'ar_AR',
    'Azerbaijani': 'az_AZ',
    'Bengali': 'bn_IN',
    'Burmese': 'my_MM',
    'Chinese': 'zh_CN',
    'Croatian': 'hr_HR',
    'Czech': 'cs_CZ',
    'Dutch': 'nl_XX',
    'English': 'en_XX',
    'Estonian': 'et_EE',
    'Finnish': 'fi_FI',
    'French': 'fr_XX',
    'Galician': 'gl_ES',
    'Georgian': 'ka_GE',
    'German': 'de_DE',
    'Gujarati': 'gu_IN',
    'Hebrew': 'he_IL',
    'Hindi': 'hi_IN',
    'Indonesian': 'id_ID',
    'Italian': 'it_IT',
    'Japanese': 'ja_XX',
    'Kazakh': 'kk_KZ',
    'Khmer': 'km_KH',
    'Korean': 'ko_KR',
    'Latvian': 'lv_LV',
    'Lithuanian': 'lt_LT',
    'Macedonian': 'mk_MK',
    'Malayalam': 'ml_IN',
    'Marathi': 'mr_IN',
    'Mongolian': 'mn_MN',
    'Nepali': 'ne_NP',
    'Pashto': 'ps_AF',
    'Persian': 'fa_IR',
    'Polish': 'pl_PL',
    'Portuguese': 'pt_XX',
    'Romanian': 'ro_RO',
    'Russian': 'ru_RU',
    'Sinhala': 'si_LK',
    'Slovene': 'sl_SI',
    'Spanish': 'es_XX',
    'Swahili': 'sw_KE',
    'Swedish': 'sv_SE',
    'Tagalog': 'tl_XX',
    'Tamil': 'ta_IN',
    'Telugu': 'te_IN',
    'Thai': 'th_TH',
    'Turkish': 'tr_TR',
    'Ukrainian': 'uk_UA',
    'Urdu': 'ur_PK',
    'Vietnamese': 'vi_VN',
    'Xhosa': 'xh_ZA',
    }
